import { createIndexer, createLocalCache } from "@latticexyz/recs";
import { defineInventoryIndexComponent } from "./InventoryIndex";
import { definePlayerMeshComponent } from "./PlayerMesh";
import { defineSelectedSlotComponent } from "./SelectedSlot";
import { definePlayerPositionComponent } from "./PlayerPosition";
import { defineLocalPlayerPositionComponent } from "./LocalPlayerPosition";
import { definePlayerDirectionComponent } from "./PlayerDirection";
import { definePlayerLastMessage } from "./PlayerLastMessage";
import { definePlayerRelayerChunkPositionComponent } from "./PlayerRelayerChunkPosition";
import { defineUIComponent } from "./UI";
import { defineCraftingTableComponent } from "./CraftingTable";
import { defineTutorialComponent } from "./Tutorial";
import { definePreTeleportPositionComponent } from "./PreTeleportPosition";
import { defineSoundComponent } from "./Sound";
import { world } from "../world";

export const SelectedSlot = defineSelectedSlotComponent(world);
export const CraftingTable = defineCraftingTableComponent(world);
export const PlayerPosition = definePlayerPositionComponent(world);
export const LocalPlayerPosition = defineLocalPlayerPositionComponent(world);
export const PlayerRelayerChunkPosition = createIndexer(definePlayerRelayerChunkPositionComponent(world));
export const PlayerDirection = definePlayerDirectionComponent(world);
export const PlayerLastMessage = definePlayerLastMessage(world);
export const PlayerMesh = definePlayerMeshComponent(world);
export const UI = defineUIComponent(world);
export const InventoryIndex = createIndexer(defineInventoryIndexComponent(world));
export const Tutorial = defineTutorialComponent(world);
export const PreTeleportPosition = definePreTeleportPositionComponent(world);
export const Sounds = defineSoundComponent(world);
