import { defineItemComponent } from "./ItemComponent";
import { defineItemPrototypeComponent } from "./ItemPrototypeComponent";
import { definePositionComponent } from "./PositionComponent";
import { definePosition2DComponent } from "./Position2DComponent";
import { defineOwnedByComponent } from "./OwnedByComponent";
import { defineGameConfigComponent } from "./GameConfigComponent";
import { defineRecipeComponent } from "./RecipeComponent";
import { defineLoadingStateComponent } from "./LoadingStateComponent";
import { defineOccurrenceComponent } from "./OccurrenceComponent";
import { defineStakeComponent } from "./StakeComponent";
import { defineClaimComponent } from "./ClaimComponent";
import { defineNameComponent } from "./NameComponent";
import { definePluginComponent } from "./PluginComponent";
import { definePluginRegistryComponent } from "./PluginRegistryComponent";
import { defineChunkComponent } from "./ChunkComponent";
import { world } from "../world";

export const Position = definePositionComponent(world);
export const Position2D = definePosition2DComponent(world);
export const Item = defineItemComponent(world);
export const Chunk = defineChunkComponent(world);
export const ItemPrototype = defineItemPrototypeComponent(world);
export const Name = defineNameComponent(world);
export const OwnedBy = defineOwnedByComponent(world);
export const GameConfig = defineGameConfigComponent(world);
export const Recipe = defineRecipeComponent(world);
export const LoadingState = defineLoadingStateComponent(world);
export const Occurrence = defineOccurrenceComponent(world);
export const Stake = defineStakeComponent(world);
export const Claim = defineClaimComponent(world);
export const Plugin = definePluginComponent(world);
export const PluginRegistry = definePluginRegistryComponent(world);
