// TODO: we need to create a tileset from the OPCraft textures and then map this enum to the indices in the tileset
export enum BlockType {
  Air,
  Grass,
  Dirt,
  Log,
  Stone,
  Sand,
  Glass,
  Water,
  Cobblestone,
  MossyCobblestone,
  Coal,
  Crafting,
  Iron,
  Gold,
  Diamond,
  Leaves,
  Planks,
  RedFlower,
  GrassPlant,
  OrangeFlower,
  MagentaFlower,
  LightBlueFlower,
  LimeFlower,
  PinkFlower,
  GrayFlower,
  LightGrayFlower,
  CyanFlower,
  PurpleFlower,
  BlueFlower,
  GreenFlower,
  BlackFlower,
  Kelp,
  Wool,
  OrangeWool,
  MagentaWool,
  LightBlueWool,
  YellowWool,
  LimeWool,
  PinkWool,
  GrayWool,
  LightGrayWool,
  CyanWool,
  PurpleWool,
  BlueWool,
  BrownWool,
  GreenWool,
  RedWool,
  BlackWool,
  Sponge,
  Snow,
  Clay,
  Bedrock,
  Bricks,
}

export const Textures: { [key: number]: number } = {
  [BlockType.Grass]: 40,
  [BlockType.Dirt]: 42,
};
