# .github/workflows/test-build.yml
name: Test client build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Build client
        run: yarn workspace client run build
